image: node:18

pipelines:
  default:
    - parallel:
        - step:
            name: Build Application
            caches:
              - node
            script:
              - npm install
              - npm run build
              - npm run export  # Added to generate the out directory
              - ls -la  # Debug: Confirm out directory
        - step:
            name: Lint Code
            script:
              - npm install
              - npm run lint
            caches:
              - node
  branches:
    main:
      - step:
          name: Build Application
          caches:
            - node
          script:
            - npm install
            - npm run build
            - npm run export  # Generate static export
            - ls -la  # Debug: Confirm out directory
          artifacts:
            - out/**  # Use out directory as artifact
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to Production
          deployment: Production
          # trigger: manual  # Uncomment if manual triggering is needed
          clone:
            enabled: false
          script:
            - ls -la  # Debug: Check if out is available
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: 'frontend-admin-pekatafoods'
                LOCAL_PATH: 'out'  # Deploy the out directory
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: 'E1HK1UIRLVTHTY'