image: node:18

pipelines:
  default:
    - parallel:
        - step:
            name: Build Application
            caches:
              - node
            script:
              - export NODE_ENV=production
              - export NEXT_PUBLIC_API_URL=https://backend.pekatafoods.com/api/v1
              - rm -rf node_modules package-lock.json .env.local .env
              - yarn install
              - yarn build
              - ls -la  # Debug: Confirm out directory
        - step:
            name: Lint Code
            script:
              - yarn install
              - yarn lint
            caches:
              - node
  branches:
    production:
      - step:
          name: Build Application
          caches:
            - node
          script:
            - export NODE_ENV=production
            - export NEXT_PUBLIC_API_URL=https://backend.pekatafoods.com/api/v1
            - rm -rf node_modules package-lock.json .env.local .env
            - yarn install
            - yarn build
            - ls -la  # Debug: Confirm out directory
          artifacts:
            - out/**  # Use out directory as the artifact
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to Production
          deployment: Production
          # trigger: manual  # Uncomment if manual triggering is needed
          clone:
            enabled: false
          script:
            - ls -la  # Debug: Check if out directory is available
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: 'frontend-admin-pekatafoods'
                LOCAL_PATH: 'out'  # Deploy the out directory
                # Sin S3_PATH - sube a raíz del bucket
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: 'E1HK1UIRLVTHTY'
                PATHS: '/index.html'  # Solo invalidar index.html en raíz